name: CI

on: [push, pull_request]

jobs:
  build:
    name: Poltergeist (${{matrix.runtime}} ${{matrix.configuration}})
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest]
        configuration: ['debug', 'release']
        include:
          - os: windows-latest
            runtime: 'win-x64'

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore -r ${{matrix.runtime}}

    - name: Build editor
      run: dotnet publish -c ${{matrix.configuration}} -r ${{matrix.runtime}} --no-restore Poltergeist.Editor

    - name: Build sandbox
      run: dotnet publish -c ${{matrix.configuration}} -r ${{matrix.runtime}} --no-restore Poltergeist.Sandbox

    - name: Test
      run: dotnet test -c ${{matrix.configuration}} -r ${{matrix.runtime}}

    - name: Upload editor
      uses: actions/upload-artifact@v2
      with:
        name: Poltergeist.Editor (${{matrix.runtime}} ${{matrix.configuration}})
        path: Poltergeist.Editor/bin/${{matrix.configuration}}/net5.0/${{matrix.runtime}}/publish

    - name: Upload sandbox
      uses: actions/upload-artifact@v2
      with:
        name: Poltergeist.Sandbox (${{matrix.runtime}} ${{matrix.configuration}})
        path: Poltergeist.Sandbox/bin/${{matrix.configuration}}/net5.0/${{matrix.runtime}}/publish
