name: CMake

on: [push, pull_request]

jobs:
  build:
    name: Poltergeist CMake 
    runs-on: ${{matrix.os}}

    env:
      buildDir: '${{github.workspace}}/out'

    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        configuration: ['Debug', 'Release']
        include:
          - os: windows-latest
            generator: 'VS16Win64'
          - os: ubuntu-latest
            generator: 'UnixMakefiles'

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'

    - if: matrix.os == 'windows-latest'
      name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        doNotUpdateVcpkg: true
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        appendedCacheKey: ${{hashFiles('${{github.workspace}}/vcpkg.json')}}
        additionalCachedPaths: '${{env.buildDir}}/vcpkg_installed'

    - name: Build
      uses: lukka/run-cmake@v3.3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        useVcpkgToolchainFile: true
        buildWithCMake: true
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        buildDirectory: ${{env.buildDir}}
        cmakeBuildType: ${{matrix.configuration}}
        cmakeGenerator: ${{matrix.generator}}
