name: CMake

on: [push, pull_request]

jobs:
  build:
    name: Poltergeist CMake 
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest]
        configuration: ['Debug', 'Release']
        include:
          - os: windows-latest
            generator: 'VS16Win64'
          #- os: windows-latest
          #  generator: 'MSYS Makefiles'

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'

    - if: matrix.os == 'windows-latest'
      name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

    - name: 'Build'
      uses: lukka/run-cmake@v3.3
      with:
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=${{matrix.configuration}}'
        cmakeGenerator: ${{matrix.generator}}
