name: CMake

on: [push, pull_request]

jobs:
  build:
    name: Poltergeist CMake 
    runs-on: ${{matrix.os}}

    env:
      buildDir: '${{github.workspace}}/out'
      llvmLocation: '${{github.workspace}}/llvm'

    strategy:
      matrix:
        os: [windows-latest,ubuntu-20.04]
        configuration: ['Debug', 'Release']
        compiler: ['msvc','gcc','clang']
        generator: ['Visual Studio 16 2019', 'MSYS Makefiles', 'Unix Makefiles']
        exclude:
          - os: windows-latest
            generator: 'Unix Makefiles'
          - os: ubuntu-20.04
            compiler: 'msvc'
          - os: ubuntu-20.04
            generator: 'Visual Studio 16 2019'
          - os: ubuntu-20.04
            generator: 'MSYS Makefiles' 
          - compiler: 'msvc'
            generator: 'MSYS Makefiles'
          - compiler: 'gcc'
            generator: 'Visual Studio 16 2019'
          - compiler: 'clang'
            generator: 'Visual Studio 16 2019'
        include:
          - generator: 'Visual Studio 16 2019'
            cmakeshell: 'powershell'
          - generator: 'MSYS Makefiles'
            cmakeshell: 'msys2'
          - generator: 'Visual Studio 16 2019'
            cmakeshell: 'bash'

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'

    - if: matrix.os == 'ubuntu-20.04'
      name: Install dependencies
      run: |
        sudo apt update
        sudo apt install build-essential gcc-10 g++-10 clang llvm cmake libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libtinfo6

    - if: matrix.generator == 'MSYS Makefiles'
      name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    - if: matrix.compiler == 'msvc'
      name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - if: matrix.compiler == 'gcc' && matrix.os != 'windows-latest'
      shell: 'bash'
      name: Set up GCC
      run: |
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
        
    - if: matrix.compiler == 'gcc' && matrix.os == 'windows-latest'
      shell: 'msys2 {0}'
      name: Set up GCC
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV

    - if: matrix.compiler == 'clang' && matrix.os != 'windows-latest'
      name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: '${{env.llvmLocation}}'
        key: llvm-11

    - if: matrix.compiler == 'clang' && matrix.os != 'windows-latest'
      name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11"
        directory: '${{env.llvmLocation}}'
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - if: matrix.compiler == 'clang' && matrix.os != 'windows-latest'
      shell: 'bash'
      name: Enable CLANG
      run: |
        echo "CC=${{env.llvmLocation}}/bin/clang" >> $GITHUB_ENV
        echo "CXX=${{env.llvmLocation}}/bin/clang++" >> $GITHUB_ENV
        
    - if: matrix.compiler == 'clang' && matrix.os == 'windows-latest'
      shell: 'msys2 {0}'
      name: Enable CLANG
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        doNotUpdateVcpkg: true
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        appendedCacheKey: ${{matrix.os}}-${{matrix.compiler}}-${{hashFiles('vcpkg.json')}}
        additionalCachedPaths: '${{env.buildDir}}/vcpkg_installed'

    - name: Build
      uses: lukka/run-cmake@v3.3
      with:
        useShell: '${{matrix.cmakeshell}}'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        useVcpkgToolchainFile: true
        buildWithCMake: true
        buildDirectory: ${{env.buildDir}}
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        cmakeAppendedArgs: '-G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.configuration}}'
